# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-03-13 15:30:35
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    MNT2_tif = arcpy.Raster("MNT2.tif")
    Projet_Info_gdb = "C:\\Users\\dell\\Documents\\ArcGIS\\Projects\\Projet_Info\\Projet_Info.gdb"

    # Process: Aggregate (Aggregate) (sa)
    Aggrega_MNT22 = "C:\\Users\\dell\\Documents\\ArcGIS\\Projects\\Projet_Info\\Projet_Info.gdb\\Aggrega_MNT22"
    Aggregate = Aggrega_MNT22
    Aggrega_MNT22 = arcpy.sa.Aggregate(MNT2_tif, 20, "MEAN", "EXPAND", "DATA")
    Aggrega_MNT22.save(Aggregate)


    # Process: Focal Statistics (Focal Statistics) (ia)
    FocalSt_Aggr1 = "C:\\Users\\dell\\Documents\\ArcGIS\\Projects\\Projet_Info\\Projet_Info.gdb\\FocalSt_Aggr1"
    Focal_Statistics = FocalSt_Aggr1
    FocalSt_Aggr1 = arcpy.ia.FocalStatistics(Aggrega_MNT22, "Rectangle 2 2 CELL", "MEAN", "DATA", 90)
    FocalSt_Aggr1.save(Focal_Statistics)


    # Process: Générer courbes de niveau (Générer courbes de niveau) (courbes)
    arcpy.courbes.GenererCourbes(mnt_entree=FocalSt_Aggr1, cell_size=10, simplify_tolerance=5, smooth_tolerance=15, simplify_tolerance_bis=5, gdb_sortie=Projet_Info_gdb, equidistance=5, longueur_min=60, nom_sortie="Courbes_FocalST22_Aggr10_60")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dell\\Documents\\ArcGIS\\Projects\\Projet_Info\\Projet_Info.gdb", workspace="C:\\Users\\dell\\Documents\\ArcGIS\\Projects\\Projet_Info\\Projet_Info.gdb"):
        Model()
